version: "3.8"
services:
  # server:
  #     image: server
  #     container_name: server
  #     ports:
  #       - "5072:8080"
  #     environment:
  #       - ASPNETCORE_ENVIRONMENT=Development
  #     build:
  #       context: ../server
  #       dockerfile: ../docker/Dockerfiles/Server.Dockerfile
  #     networks:
  #       - mynetwork
  #     depends_on:
  #       - postgres

  # postgres:
  #   image: postgres
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: essentialdb
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - mynetwork
      
  client:
    image: client
    container_name: client
    build:
      context: ../client
      dockerfile: ../docker/Dockerfiles/Client.Dockerfile
    hostname: client
    ports:
      - "3000:3000"
    env_file:
      - .env

# volumes:
#   pgdata:

networks:
  mynetwork:
    driver: bridge